// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraDesafio.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251123223039_JogosCadastros")]
    partial class JogosCadastros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Jogo", b =>
                {
                    b.Property<int>("IDJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDJogo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDJogo"), 1L, 1);

                    b.Property<string>("Disponibilidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Disponilidade");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Genero");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Plataforma");

                    b.HasKey("IDJogo");

                    b.ToTable("Jogos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
