// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraDesafio.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251124041112_DateNull")]
    partial class DateNull
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Aluguel", b =>
                {
                    b.Property<int>("IDAluguel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDAluguel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDAluguel"), 1L, 1);

                    b.Property<DateTime>("DataAluguel")
                        .HasColumnType("datetime")
                        .HasColumnName("DataAluguel");

                    b.Property<DateTime?>("DataDevolucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DataDevolucao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.HasKey("IDAluguel");

                    b.HasIndex("IDCliente");

                    b.ToTable("Alugueis", (string)null);
                });

            modelBuilder.Entity("Dominio.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCliente"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefone");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Dominio.Jogo", b =>
                {
                    b.Property<int>("IDJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDJogo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDJogo"), 1L, 1);

                    b.Property<string>("Disponibilidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Disponibilidade");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Genero");

                    b.Property<int?>("IDAluguel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Plataforma");

                    b.HasKey("IDJogo");

                    b.HasIndex("IDAluguel");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("Dominio.Aluguel", b =>
                {
                    b.HasOne("Dominio.Cliente", "Cliente")
                        .WithMany("Alugueis")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Dominio.Jogo", b =>
                {
                    b.HasOne("Dominio.Aluguel", "Aluguel")
                        .WithMany("Jogos")
                        .HasForeignKey("IDAluguel")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluguel");
                });

            modelBuilder.Entity("Dominio.Aluguel", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("Dominio.Cliente", b =>
                {
                    b.Navigation("Alugueis");
                });
#pragma warning restore 612, 618
        }
    }
}
